blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/ss0923/limb.tmux/discussions
    about: Ask questions or propose ideas before filing a feature request
